package constants

// 定义常见的 HTTP 头部常量
const (
	HeaderAuthorization                   = "Authorization"                       // HTTP 请求头字段，携带认证信息
	HeaderProxyAuthenticate               = "Proxy-Authenticate"                  // HTTP 响应头字段，要求客户端提供认证信息以访问代理服务器
	HeaderProxyAuthorization              = "Proxy-Authorization"                 // HTTP 请求头字段，携带代理服务器的认证信息
	HeaderWWWAuthenticate                 = "WWW-Authenticate"                    // HTTP 响应头字段，表示服务器要求客户端进行认证
	HeaderAge                             = "Age"                                 // HTTP 响应头字段，表示从原始服务器生成响应以来的秒数
	HeaderCacheControl                    = "Cache-Control"                       // HTTP 请求/响应头字段，用于指定缓存机制
	HeaderClearSiteData                   = "Clear-Site-Data"                     // HTTP 响应头字段，清除用户数据（如缓存、cookies）
	HeaderExpires                         = "Expires"                             // HTTP 响应头字段，指定响应过期的日期和时间
	HeaderPragma                          = "Pragma"                              // HTTP 请求/响应头字段，控制缓存机制
	HeaderWarning                         = "Warning"                             // HTTP 响应头字段，提供关于缓存或状态的警告信息
	HeaderAcceptCH                        = "Accept-CH"                           // HTTP 响应头字段，指定客户端提示的字段
	HeaderAcceptCHLifetime                = "Accept-CH-Lifetime"                  // HTTP 响应头字段，指定客户端提示的字段的生存时间
	HeaderContentDPR                      = "Content-DPR"                         // HTTP 响应头字段，指定内容的设备像素比
	HeaderDPR                             = "DPR"                                 // HTTP 请求头字段，指定客户端的设备像素比
	HeaderEarlyData                       = "Early-Data"                          // HTTP 请求头字段，指示请求使用的是 0-RTT 早期数据
	HeaderSaveData                        = "Save-Data"                           // HTTP 请求头字段，表示客户端想要保存数据
	HeaderViewportWidth                   = "Viewport-Width"                      // HTTP 请求头字段，指定客户端的视口宽度
	HeaderWidth                           = "Width"                               // HTTP 请求头字段，指定资源的显示宽度
	HeaderETag                            = "ETag"                                // HTTP 响应头字段，提供资源的实体标签（ETag）
	HeaderIfMatch                         = "If-Match"                            // HTTP 请求头字段，仅在给定的实体标记匹配时执行请求
	HeaderIfModifiedSince                 = "If-Modified-Since"                   // HTTP 请求头字段，仅在给定日期后资源被修改时执行请求
	HeaderIfNoneMatch                     = "If-None-Match"                       // HTTP 请求头字段，指示仅在不匹配给定的实体标签时返回资源
	HeaderIfUnmodifiedSince               = "If-Unmodified-Since"                 // HTTP 请求头字段，仅在给定日期后资源未被修改时执行请求
	HeaderLastModified                    = "Last-Modified"                       // HTTP 响应头字段，指示资源的最后修改日期
	HeaderVary                            = "Vary"                                // HTTP 响应头字段，指示缓存如何根据请求头部字段生成缓存副本
	HeaderConnection                      = "Connection"                          // HTTP 请求/响应头字段，控制连接管理（例如保持连接）
	HeaderKeepAlive                       = "Keep-Alive"                          // HTTP 响应头字段，控制持久连接的参数
	HeaderAccept                          = "Accept"                              // HTTP 请求头字段，指定客户端可接受的响应媒体类型
	HeaderAcceptCharset                   = "Accept-Charset"                      // HTTP 请求头字段，指定客户端可接受的字符集
	HeaderAcceptEncoding                  = "Accept-Encoding"                     // HTTP 请求头字段，指定客户端可接受的内容编码
	HeaderAcceptLanguage                  = "Accept-Language"                     // HTTP 请求头字段，指定客户端可接受的语言
	HeaderCookie                          = "Cookie"                              // HTTP 请求头字段，向服务器发送客户端的 cookies
	HeaderExpect                          = "Expect"                              // HTTP 请求头字段，指示客户端期望服务器的行为
	HeaderMaxForwards                     = "Max-Forwards"                        // HTTP 请求头字段，指定请求可以通过的代理服务器或网关的最大数量
	HeaderSetCookie                       = "Set-Cookie"                          // HTTP 响应头字段，指示服务器向客户端设置 cookies
	HeaderAccessControlAllowCredentials   = "Access-Control-Allow-Credentials"    // CORS 响应头字段，指示是否可以使用凭据
	HeaderAccessControlAllowHeaders       = "Access-Control-Allow-Headers"        // CORS 响应头字段，指定可以在实际请求中使用的首部字段
	HeaderAccessControlAllowMethods       = "Access-Control-Allow-Methods"        // CORS 响应头字段，指定实际请求可以使用的 HTTP 方法
	HeaderAccessControlAllowOrigin        = "Access-Control-Allow-Origin"         // CORS 响应头字段，指定允许访问资源的来源
	HeaderAccessControlExposeHeaders      = "Access-Control-Expose-Headers"       // CORS 响应头字段，指定可以访问的响应头字段
	HeaderAccessControlMaxAge             = "Access-Control-Max-Age"              // CORS 响应头字段，指定预检请求的结果可以缓存的时间
	HeaderAccessControlRequestHeaders     = "Access-Control-Request-Headers"      // CORS 请求头字段，指定在实际请求中使用的首部字段
	HeaderAccessControlRequestMethod      = "Access-Control-Request-Method"       // CORS 请求头字段，指定在实际请求中使用的 HTTP 方法
	HeaderOrigin                          = "Origin"                              // HTTP 请求头字段，指示请求的来源
	HeaderTimingAllowOrigin               = "Timing-Allow-Origin"                 // HTTP 响应头字段，指定允许访问资源时间数据的来源
	HeaderXPermittedCrossDomainPolicies   = "X-Permitted-Cross-Domain-Policies"   // HTTP 响应头字段，指定允许跨域策略文件的类型
	HeaderDNT                             = "DNT"                                 // HTTP 请求头字段，表示用户不希望被跟踪
	HeaderTk                              = "Tk"                                  // HTTP 响应头字段，表示跟踪状态
	HeaderContentDisposition              = "Content-Disposition"                 // HTTP 响应头字段，指定内容的呈现方式（如附件）
	HeaderContentEncoding                 = "Content-Encoding"                    // HTTP 响应头字段，指定内容的编码方式
	HeaderContentLanguage                 = "Content-Language"                    // HTTP 响应头字段，指定内容的语言
	HeaderContentLength                   = "Content-Length"                      // HTTP 请求/响应头字段，指示请求或响应主体的字节长度
	HeaderContentLocation                 = "Content-Location"                    // HTTP 响应头字段，指示资源的替代位置
	HeaderContentType                     = "Content-Type"                        // HTTP 请求/响应头字段，指定请求或响应主体的媒体类型
	HeaderForwarded                       = "Forwarded"                           // HTTP 请求头字段，表示代理服务器的传递信息
	HeaderVia                             = "Via"                                 // HTTP 请求/响应头字段，表示代理或网关服务器的传递信息
	HeaderXForwardedFor                   = "X-Forwarded-For"                     // HTTP 请求头字段，表示客户端的 IP 地址（通过代理服务器）
	HeaderXForwardedHost                  = "X-Forwarded-Host"                    // HTTP 请求头字段，表示客户端的原始主机
	HeaderXForwardedProto                 = "X-Forwarded-Proto"                   // HTTP 请求头字段，表示客户端的原始协议（HTTP 或 HTTPS）
	HeaderXForwardedProtocol              = "X-Forwarded-Protocol"                // HTTP 请求头字段，表示客户端的原始协议（HTTP 或 HTTPS）
	HeaderXForwardedSsl                   = "X-Forwarded-Ssl"                     // HTTP 请求头字段，表示客户端是否使用 SSL（通过代理服务器）
	HeaderXUrlScheme                      = "X-Url-Scheme"                        // HTTP 请求头字段，表示请求的 URL 协议
	HeaderLocation                        = "Location"                            // HTTP 响应头字段，指示资源的重定向位置
	HeaderFrom                            = "From"                                // HTTP 请求头字段，表示请求发起者的电子邮件地址
	HeaderHost                            = "Host"                                // HTTP 请求头字段，指定请求目标的主机和端口号
	HeaderReferer                         = "Referer"                             // HTTP 请求头字段，表示当前请求的来源
	HeaderReferrerPolicy                  = "Referrer-Policy"                     // HTTP 请求头字段，控制 Referer 头字段的发送
	HeaderUserAgent                       = "User-Agent"                          // HTTP 请求头字段，表示客户端的用户代理信息
	HeaderAllow                           = "Allow"                               // HTTP 响应头字段，指定资源支持的 HTTP 方法
	HeaderServer                          = "Server"                              // HTTP 响应头字段，表示服务器软件的信息
	HeaderAcceptRanges                    = "Accept-Ranges"                       // HTTP 响应头字段，指示服务器支持的范围请求
	HeaderContentRange                    = "Content-Range"                       // HTTP 响应头字段，指示部分响应的范围
	HeaderIfRange                         = "If-Range"                            // HTTP 请求头字段，指示在指定的实体标记匹配时执行范围请求
	HeaderRange                           = "Range"                               // HTTP 请求头字段，指定请求的字节范围
	HeaderContentSecurityPolicy           = "Content-Security-Policy"             // HTTP 响应头字段，定义内容安全策略
	HeaderContentSecurityPolicyReportOnly = "Content-Security-Policy-Report-Only" // HTTP 响应头字段，定义内容安全策略（仅报告模式）
	HeaderCrossOriginResourcePolicy       = "Cross-Origin-Resource-Policy"        // HTTP 响应头字段，控制跨域资源策略
	HeaderExpectCT                        = "Expect-CT"                           // HTTP 响应头字段，指示证书透明性策略
	HeaderFeaturePolicy                   = "Feature-Policy"                      // HTTP 响应头字段，控制浏览器特性策略
	HeaderPublicKeyPins                   = "Public-Key-Pins"                     // HTTP 响应头字段，表示公钥钉扎策略
	HeaderPublicKeyPinsReportOnly         = "Public-Key-Pins-Report-Only"         // HTTP 响应头字段，表示公钥钉扎策略（仅报告模式）
	HeaderStrictTransportSecurity         = "Strict-Transport-Security"           // HTTP 响应头字段，指示浏览器强制使用 HTTPS 访问
	HeaderUpgradeInsecureRequests         = "Upgrade-Insecure-Requests"           // HTTP 请求头字段，表示客户端愿意接收 HTTPS 响应
	HeaderXContentTypeOptions             = "X-Content-Type-Options"              // HTTP 响应头字段，防止 MIME 类型嗅探
	HeaderXDownloadOptions                = "X-Download-Options"                  // HTTP 响应头字段，防止下载文件自动执行
	HeaderXFrameOptions                   = "X-Frame-Options"                     // HTTP 响应头字段，防止网页被嵌入到 iframe 中
	HeaderXPoweredBy                      = "X-Powered-By"                        // HTTP 响应头字段，指示服务器使用的技术栈
	HeaderXXSSProtection                  = "X-XSS-Protection"                    // HTTP 响应头字段，启用 XSS 过滤
	HeaderLastEventID                     = "Last-Event-ID"                       // HTTP 请求头字段，指定最后一个事件 ID
	HeaderNEL                             = "NEL"                                 // HTTP 响应头字段，表示网络错误日志的策略
	HeaderPingFrom                        = "Ping-From"                           // HTTP 请求头字段，指示 Ping 请求的来源
	HeaderPingTo                          = "Ping-To"                             // HTTP 请求头字段，指示 Ping 请求的目标
	HeaderReportTo                        = "Report-To"                           // HTTP 响应头字段，表示错误报告的目标
	HeaderTE                              = "TE"                                  // HTTP 请求头字段，指定传输编码的接受方式
	HeaderTrailer                         = "Trailer"                             // HTTP 请求/响应头字段，指定在消息主体之后传输的头字段
	HeaderTransferEncoding                = "Transfer-Encoding"                   // HTTP 响应头字段，指示传输编码方式（如分块编码）
	HeaderSecWebSocketAccept              = "Sec-WebSocket-Accept"                // WebSocket 响应头字段，表示接受的 WebSocket 连接
	HeaderSecWebSocketExtensions          = "Sec-WebSocket-Extensions"            // WebSocket 响应头字段，表示使用的 WebSocket 扩展
	HeaderSecWebSocketKey                 = "Sec-WebSocket-Key"                   // WebSocket 请求头字段，表示客户端生成的密钥
	HeaderSecWebSocketProtocol            = "Sec-WebSocket-Protocol"              // WebSocket 请求头字段，表示使用的 WebSocket 子协议
	HeaderSecWebSocketVersion             = "Sec-WebSocket-Version"               // WebSocket 请求头字段，表示使用的 WebSocket 协议版本
	HeaderAcceptPatch                     = "Accept-Patch"                        // HTTP 响应头字段，指示服务器支持的部分更新方法
	HeaderAcceptPushPolicy                = "Accept-Push-Policy"                  // HTTP 响应头字段，表示客户端可接受的推送策略
	HeaderAcceptSignature                 = "Accept-Signature"                    // HTTP 响应头字段，表示客户端支持的签名算法
	HeaderAltSvc                          = "Alt-Svc"                             // HTTP 响应头字段，表示替代服务的信息
	HeaderDate                            = "Date"                                // HTTP 请求/响应头字段，指示消息发送的日期和时间
	HeaderIndex                           = "Index"                               // HTTP 请求头字段，指定索引页
	HeaderLargeAllocation                 = "Large-Allocation"                    // HTTP 响应头字段，表示为大分配提供的内存大小
	HeaderLink                            = "Link"                                // HTTP 响应头字段，表示文档的关系类型
	HeaderPushPolicy                      = "Push-Policy"                         // HTTP 响应头字段，表示服务器使用的推送策略
	HeaderRetryAfter                      = "Retry-After"                         // HTTP 响应头字段，表示客户端应等待的时间
	HeaderServerTiming                    = "Server-Timing"                       // HTTP 响应头字段，表示服务器端性能的指标
	HeaderSignature                       = "Signature"                           // HTTP 请求/响应头字段，表示请求或响应的数字签名
	HeaderSignedHeaders                   = "Signed-Headers"                      // HTTP 响应头字段，指示签名的 HTTP 头字段
	HeaderSourceMap                       = "SourceMap"                           // HTTP 响应头字段，表示 JavaScript 的源映射
	HeaderUpgrade                         = "Upgrade"                             // HTTP 请求/响应头字段，表示协议升级
	HeaderXDNSPrefetchControl             = "X-DNS-Prefetch-Control"              // HTTP 响应头字段，控制 DNS 预获取行为
	HeaderXPingback                       = "X-Pingback"                          // HTTP 响应头字段，表示 Pingback 的 URL
	HeaderXRequestID                      = "X-Request-ID"                        // HTTP 请求/响应头字段，表示请求的唯一标识符
	HeaderXRequestedWith                  = "X-Requested-With"                    // HTTP 请求头字段，指示请求是由 Ajax 发起的
	HeaderXRobotsTag                      = "X-Robots-Tag"                        // HTTP 响应头字段，控制搜索引擎抓取行为
	HeaderXUACompatible                   = "X-UA-Compatible"                     // HTTP 响应头字段，指定浏览器的兼容性模式
)
